### PR TITLE
Implementation of multiple new features

### PR DESCRIPTION
**Pull request by bendikro**
Hi

I had actually found your email and was going to email you when I  found your new git repo! I started on working on this many weeks ago, and didn't expect you to still be interested in working on the errata package, but I guess I was wrong ;-)

As I noticed your github repo today, all of the functionality in the current HEAD was already implemented before I found your latest commits. I noticed you implemented a new package option `mark`, which I had already implemented as `inlinemarks`.  As you haven't updated the ctan code with the latest changes, I guess it's not a problem to kep the name `inlinemarks`? That would match the name `inlinechanges` which is another option I've implemented.
Also, I didn't add the new `no*` options you implemented, as the current package option handling can take key/values, so instead of passing `nomargins`, you can pass `margins=false`
I think the other changes you did lately has been incorporated in this commit.

The main reason I started modifying the code was to make the errata information customizable. You can see an example of how the errata list can look in  `erratatest.pdf`. However, I've tried to ensure that the default settings produce the same output as version v0.3.

I hope you don't mind the changes to the documentation. I just find the standard look (of most LaTeX packages) to be incredibly boring.

The changes are as follows:
- Hyperref and cleveref support
- Support for using marginnote in environments where marginpar cannot be used.
- Implemented support for customizing the format of most of the (meta-)data in the
  errata list and margin/footnotes.
- Rewritten much of the docs using tcolorbox's documentation library
- Added erratatest.tex which can be used to test and show examples.
- Changed package option handling to kvoptions package
- Added many new package options:
  - environmenttestmode: To set to safety level for when to use marginpar vs marginnote
  - inlinemarks: To specify whether the errata changes should be enclosed in []
  - inlinemarkdefault: To specify the default value for the errata commands, which can be
    overridden by specifying a custom inlinemark value explicitly in the errata command.
  - inlinechanges: To specify whether the change of each erratum should be reflected in the
    document text or if the text should stay unchanged.
  - inlinechangedefault: To specify the default value for the errata commands, which can be
    overridden by specifying a custom inlinechange value explicitly in the errata command.
  - margindefault: Allows setting the default setting for whether a margin note should be
    created for each erratum.
  - marginargsdefault: Extra arguments which can be passed to the marginnote formatter for
    all the commands
  - style: Allows setting a different (predefined) set of formatter values. Currently only
    one other style exists: detailed
  - requiredescription: By setting this to false, the errata commands are defined without
    the mandatory description argument.
- Added new optional command arguments:
  - inlinechange: To override the inlinemarkdefault
  - inlinemark: To override the inlinemarkdefault
  - marginargs: Extra arguments which can be passed to the marginnote formatter
  - label: Allows specifying a custom label name to define for the new erratum
  - uselabel: Allows specifying a label name which will be used instead of the
    default label (errataX where X is the erratum number). This is required in
    Special environments.
  - margin: Allows overriding the margindefault value to specify whether this erratum should
    add a margin note.
  - marginargs: Allows overriding the marginargsdefault for a command.
  - usemarginnote: Allows to force the use of marginnote and optionally specify a value to
    vertically shift the marginnote. This is required when multiple marginnotes are overlapping.

### CODE REVIEW

**Comment by kohlhase** [comment]
Dear Bendik,

what a surprise to see so much interest in the old errata packge after
so long.

Just two weeks ago, someone else noted problems in the package, which
triggered me to take another look. It seems that you have done a more
thorough job than I have. I would be very happy to pass on the
maintainership to you, I just did not want to leave the package in such
a bad state, but am not really interested in maintaining it further. 

If you are OK with this, you can just import the repos and make a
submission to CTAN.

Michael

On 17/04/15 03:35, Bendik wrote:

> Hi
> 
> I had actually found your email and was going to email you when I
> found your new git repo! I started on working on this many weeks ago,
> and didn't expect you to still be interested in working on the errata
> package, but I guess I was wrong ;-)
> 
> As I noticed your github repo today, all of the functionality in the
> current HEAD was already implemented before I found your latest
> commits. I noticed you implemented a new package option |mark|, which
> I had already implemented as |inlinemarks|. As you haven't updated the
> ctan code with the latest changes, I guess it's not a problem to kep
> the name |inlinemarks|? That would match the name |inlinechanges|
> which is another option I've implemented.
> Also, I didn't add the new |no*| options you implemented, as the
> current package option handling can take key/values, so instead of
> passing |nomargins|, you can pass |margins=false|
> I think the other changes you did lately has been incorporated in this
> commit.
> 
> The main reason I started modifying the code was to make the errata
> information customizable. You can see an example of how the errata
> list can look in |erratatest.pdf|. However, I've tried to ensure that
> the default settings produce the same output as version v0.3.
> 
> I hope you don't mind the changes to the documentation. I just find
> the standard look (of most LaTeX packages) to be incredibly boring.
> 
> The changes are as follows:
> - Hyperref and cleveref support
> - Support for using marginnote in environments where marginpar
>   cannot be used.
> - Implemented support for customizing the format of most of the
>   (meta-)data in the errata list and margin/footnotes.
> - Rewritten much of the docs using tcolorbox's documentation library
> - Added erratatest.tex which can be used to test and show examples.
> - Changed package option handling to kvoptions package
> - Added many new package options:
>     o environmenttestmode: To set to safety level for when to use
>       marginpar vs marginnote
>     o inlinemarks: To specify whether the errata changes should be
>       enclosed in []
>     o inlinemarkdefault: To specify the default value for the errata
>       commands, which can be overridden by specifying a custom
>       inlinemark value explicitly in the errata command.
>     o inlinechanges: To specify whether the change of each erratum
>       should be reflected in the document text or if the text should
>       stay unchanged.
>     o inlinechangedefault: To specify the default value for the
>       errata commands, which can be overridden by specifying a
>       custom inlinechange value explicitly in the errata command.
>     o margindefault: Allows setting the default setting for whether
>       a margin note should be created for each erratum.
>     o marginargsdefault: Extra arguments which can be passed to the
>       marginnote formatter for all the commands
>     o style: Allows setting a different (predefined) set of
>       formatter values. Currently only one other style exists: detailed
>     o requiredescription: By setting this to false, the errata
>       commands are defined without the mandatory description argument.
> - Added new optional command arguments:
>     o inlinechange: To override the inlinemarkdefault
>     o inlinemark: To override the inlinemarkdefault
>     o marginargs: Extra arguments which can be passed to the
>       marginnote formatter
>     o label: Allows specifying a custom label name to define for the
>       new erratum
>     o uselabel: Allows specifying a label name which will be used
>       instead of the default label (errataX where X is the erratum
>       number). This is required in Special environments.
>     o margin: Allows overriding the margindefault value to specify
>       whether this erratum should add a margin note.
>     o marginargs: Allows overriding the marginargsdefault for a command.
>     o usemarginnote: Allows to force the use of marginnote and
>       optionally specify a value to vertically shift the marginnote.
>       This is required when multiple marginnotes are overlapping.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
>   https://github.com/KWARC/LaTeX-errata/pull/2
> 
> ```
>     Commit Summary
> ```
> - Implementation of multiple new features
>   
>   ```
>   File Changes
>   ```
> - _M_ Makefile
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-0 (31)
> - _M_ errata.dtx
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-1 (1720)
> - _M_ errata.ins
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-2 (29)
> - _M_ errata.pdf
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-3 (0)
> - _M_ errata.sty
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-4 (662)
> - _A_ erratatest.pdf
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-5 (0)
> - _A_ erratatest.tex
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-6 (461)
> - _A_ lib/Makefile.ctan
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-7 (72)
> - _A_ lib/Makefile.in
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-8 (98)
> - _A_ lib/Makefile.vars
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-9 (37)
> - _A_ stringformatter.sty
>   https://github.com/KWARC/LaTeX-errata/pull/2/files#diff-10 (76)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/KWARC/LaTeX-errata/pull/2.patch
> - https://github.com/KWARC/LaTeX-errata/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KWARC/LaTeX-errata/pull/2.

## 

---

 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   

##  m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase

**Comment by bendikro** [comment]
###### Hi Michael

I really did not intend to take over the project, or the maintainership for that matter, but if you're not really interested in maintaining I guess it's better that I step in. 
I have some mixed feelings about that though, as working on this package has been some of the most painful development I've experienced. However, I think I got the hang of it now (or at least enough), and should be able to maintain this without too much life-threatening stress.

I'd appreciate if you would still be available though, as you could probably provide some input on useful features and alternative use cases on how the package could be used.

What about creating a github organization for the project?

**Comment by bendikro** [comment]
###### About  this pull request

There are a few things I forgot to mention. First, the current state of the documentation after the changes I've made is not 100% complete, such as the package and command options which could probably be better documented. Also, there could be more examples showing how to customize the different keys using the formatters.

Also, I found out that the lib/Makefile.in does not properly handle compiling an example file with .tex extension, so that may not properly compile for you. I've fixed that locally, and made further changes which allows to customize the errata list formating as a table. I'll push these changes after I've cleaned up a bit.

About the short list you wrote under `Limitations` on possible future improvements:

> It would be nice to have:
> - the erratum marks configurable by a user-defined macro (e.g. for using colors instead of square brackets)

I did not implement this, but this should be easy to fix by creating a new inlinemark formatter

> - erratum markup show the old version next to the new ones in place (MS Word and google docs do a nice job of this in change mode)

Good suggestion. I did actually consider this when looking at errata examples, but I didn't get as far as looking at implementing it. I'd like this feature too. 

> - hyperlinking errata marks to the printed errata

The hyperlink support I implemented do not link from the corrected text, but from the margin decoration to the errata list. In the errata list, it's possible to insert the key `erratumlistitem` which links to the corrected text (as is done when setting style=detailed in `erratatest.pdf`). I guess it there could be an option to add a link from the corrected text as well, which would be useful when margins are disabled.

**Comment by kohlhase** [comment]
sorry for taking so long to come back to you, deadlines were piling up.
Comments are inline

On 22/04/15 14:16, Bendik wrote:

> ```
>         About this pull request
> ```
> 
> There are a few things I forgot to mention. First, the current state
> of the documentation after the changes I've made is not 100% complete,
> such as the package and command options which could probably be better
> documented. Also, there could be more examples showing how to
> customize the different keys using the formatters.
> 
> yes, I agree, could you do that?
> 
> Also, I found out that the lib/Makefile.in does not properly handle
> compiling an example file with .tex extension, so that may not
> properly compile for you. I've fixed that locally, and made further
> changes which allows to customize the errata list formating as a
> table. I'll push these changes after I've cleaned up a bit.
> 
> wonderful.
> 
> About the short list you wrote under |Limitations| on possible future
> improvements:
> 
> ```
> It would be nice to have:
> 
>   * the erratum marks configurable by a user-defined macro (e.g.
>     for using colors instead of square brackets)
> ```
> 
> I did not implement this,
> 
> the wonderful thing about "limitations" is that we can just collect good
> ideas until someone finds the time to implement them.
> 
> but this should be easy to fix by creating a new inlinemark formatter
> 
> good idea.
> 
> ```
>   * erratum markup show the old version next to the new ones in
>     place (MS Word and google docs do a nice job of this in change
>     mode)
> ```
> 
> Good suggestion. I did actually consider this when looking at errata
> examples, but I didn't get as far as looking at implementing it. I'd
> like this feature too.
> 
> thought sol
> 
> ```
>   * hyperlinking errata marks to the printed errata
> ```
> 
> The hyperlink support I implemented do not link from the corrected
> text, but from the margin decoration to the errata list. In the errata
> list, it's possible to insert the key |erratumlistitem| which links to
> the corrected text (as is done when setting style=detailed in
> |erratatest.pdf|). I guess it there could be an option to add a link
> from the corrected text as well, which would be useful when margins
> are disabled.
> 
> yes, I am not so sure about this either.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KWARC/LaTeX-errata/pull/2#issuecomment-95153639.

## 

---

 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   

##  m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase

**Comment by kohlhase** [comment]
On 21/04/15 17:52, Bendik wrote:

> ```
>         Hi Michael
> ```
> 
> I really did not intend to take over the project, or the
> maintainership for that matter, but if you're not really interested in
> maintaining I guess it's better that I step in.
> 
> I am not accusing you of snatching a project, but I would be very
> grateful, if you could take over as maintainer, since I really have no
> use for the package for myself any more, and you seem to have more
> energy. BTW, just in the last weeks, another person (Povl Ole Haarlev
> Olsen latex@stderr.dk) has asked about the package, so there seems to
> be some interest after all.
> 
> I have some mixed feelings about that though, as working on this
> package has been some of the most painful development I've
> experienced. However, I think I got the hang of it now (or at least
> enough), and should be able to maintain this without too much
> life-threatening stress.
> 
> good. I think we all know the pain and joy (when the pain goes away
> somewhat) of developing in LaTeX :-)
> 
> I'd appreciate if you would still be available though, as you could
> probably provide some input on useful features and alternative use
> cases on how the package could be used.
> 
> I am certainly willing to stick around with advice and suggestions, but
> I would be grateful to pass the lead on to you.
> 
> What about creating a github organization for the project?
> 
> I think that would be overkill.

I would be happy to keep hosting the repos under the KWARC organization
and make you co-owner, but you could just as well just import it into a
repository under your personal namespace, and then I would remove the
current one (which has not been publicized yet) for clarity.

Michael

## 

---

 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   

##  m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase

**Comment by kohlhase** [comment]
Once we have resolved maintainership and hosting questions (tell me what you prefer), then I guess I should just accept the pull request, and we should move on.

**Comment by bendikro** [comment]
> I am not accusing you of snatching a project, but I would be very grateful, if you could take over as maintainer, since I really have no use for the package for myself any more, and you seem to have more energy. BTW, just in the last weeks, another person (Povl Ole Haarlev Olsen latex@stderr.dk) has asked about the package, so there seems to be some interest after all.

I made these changes for my master's thesis, so I'm not sure how much use I'll have for it either in the future, but you can never know...

> > I'd appreciate if you would still be available though, as you could probably provide some input on useful features and alternative use cases on how the package could be used.
> 
> I am certainly willing to stick around with advice and suggestions, but I would be grateful to pass the lead on to you.

Then maybe we can both just stick around, and contribute with what we can :-)

I do not like to make guarantees, but I will ensure that the changes I've made will work as expected. I'd like the docs to be as good as possible, with sufficient examples and descriptions on how to use it.

> > What about creating a github organization for the project?
> 
> I think that would be overkill. I would be happy to keep hosting the repos under the KWARC organization and make you co-owner, but you could just as well just import it into a repository under your personal namespace, and then I would remove the current one (which has not been publicized yet) for clarity. 

I already have a clone on [bendikro/LaTeX-errata](https://github.com/bendikro/LaTeX-errata), but if you will stick around so that this repo, with its tickets and comments, won't suddenly disappear (as can happen for many reasons), it works fine for me to keep it under KWARC/LaTeX-errata.

If you give me write permissions, I can just push the last commit to avoid including changes that I removed in the second commit, like a few of the package options.

**Comment by kohlhase** [comment]
Dear Bendik,

seems we have a consensus. I have given you admin access (invited you
actually) to the repos. That should give you all you need.

Michael

On 28/04/15 15:57, Bendik wrote:

> ```
> I am not accusing you of snatching a project, but I would be very
> grateful, if you could take over as maintainer, since I really
> have no use for the package for myself any more, and you seem to
> have more energy. BTW, just in the last weeks, another person
> (Povl Ole Haarlev Olsen latex@stderr.dk <mailto:latex@stderr.dk>)
> has asked about the package, so there seems to be some interest
> after all.
> ```
> 
> I made these changes for my master's thesis, so I'm not sure how much
> use I'll have for it either in the future, but you can never know...
> 
> ```
>     I'd appreciate if you would still be available though, as you
>     could probably provide some input on useful features and
>     alternative use cases on how the package could be used.
> 
> I am certainly willing to stick around with advice and
> suggestions, but I would be grateful to pass the lead on to you.
> ```
> 
> Then maybe we can both just stick around, and contribute with what we
> can :-)
> 
> I do not like to make guarantees, but I will ensure that the changes
> I've made will work as expected. I'd like the docs to be as good as
> possible, with sufficient examples and descriptions on how to use it.
> 
> ```
>     What about creating a github organization for the project?
> 
> I think that would be overkill. I would be happy to keep hosting
> the repos under the KWARC organization and make you co-owner, but
> you could just as well just import it into a repository under your
> personal namespace, and then I would remove the current one (which
> has not been publicized yet) for clarity.
> ```
> 
> I already have a clone on bendikro/LaTeX-errata
> https://github.com/bendikro/LaTeX-errata, but if you will stick
> around so that this repo, with its tickets and comments, won't
> suddenly disappear (as can happen for many reasons), it works fine for
> me to keep it under KWARC/LaTeX-errata.
> 
> If you give me write permissions, I can just push the last commit to
> avoid including changes that I removed in the second commit, like a
> few of the package options.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KWARC/LaTeX-errata/pull/2#issuecomment-97072888.

## 

---

 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   

##  m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase

**Comment by bendikro** [comment]
Hi

I've cleaned up a bit and made some adjustments and it's starting to stabilize. There is still much left to be documented though, but I think it's worth pushing (No need to rebase from now on).

I tried to push to a new development branch, but I don't have the permissions(?)

> ERROR: Permission to KWARC/LaTeX-errata.git denied to bendikro.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by bendikro** [comment]
Michael

I see that we're in the group `LaTeX-errata-admins`, but this group does not have any repositories. 
I guess you intended to have this group own the `LaTeX-errata` repo?

**Comment by kohlhase** [comment]
Sorry, I hope I fixed this now.

**Comment by JohanSF** [comment]
What is the status on this package? I hand in my master thesis June 2nd and would love to use it in the two weeks after that up to my defense. Well, hopefully I don't find any mistakes and thus wont have to use it, but you never know for sure.

**Comment by kohlhase** [comment]
I have merged the pull request, please help testing.

**Comment by bendikro** [comment]
Hi

I've pushed some further changes to handle corrections containing macro calls. I also added an experimental option to track linenumbers for each erratum.

@JohanSF, what do you need that the current official (ctan) version does not provide?

**Comment by JohanSF** [comment]
I had not had time to test it, it was just my understanding that you guys were close to a breakthrough and a new stable release to CTAN. If that is the case I would of course want to use that. :) Thank you very much for the work you are doing by the way.

**Comment by bendikro** [comment]
I believe the latest code is quite stable, but from experience I know there are always unknown issues appearing. I've used the latest code on my [thesis](https://bitbucket.org/bendikro/masters-thesis/src/ee61f83262c29857e6329af14a551b3757c61ce5/thesis.pdf?at=master) using the table styling of the errata list.

The default behavior of current master HEAD should be equal to version 0.3, so if you don't need to alter the default behavior, you can just stay with v0.3. The new code allows for customizing the output to a great degree, so if you'd like to change the output, the new code is for you.

The docs and erratatest.tex shows some examples, but please ask if you have any questions on how to use the different options to customize the output.

I don't think there is any need to rush pushing the latest code to ctan. We should be absolutely certain that it doesn't break anything for existing users before updating with a new version. You can still use the new code by copying the code to your local disc. I hacket it by copying the new code to the thesis, directory and renaming errata.sty to errata2.sty. Then using with \usepackage{errata2} to avoid loading the 0.3 version. Maybe there is a better way?

**Comment by JohanSF** [comment]
Sounds like a good idea. I will report back if I have find anything out. And beautiful thesis by the way, makes me feel bad about my humble one: https://www.dropbox.com/s/wywrv5xpnc03l2p/Thesis%20-%20github.pdf?dl=0

**Comment by bendikro** [comment]
Thanks @JohanSF, it took me quite some time to write it!
Yours looks quite decent as well though, so I don't think you have to be too humble :-)

**Comment by kohlhase** [comment]
Sehr geehrter Herr Höhn,

bitte finden Sie anliegend den Entwurf für die Trauerkarte.

Wir würden gerne heute nachmittag vorbeikommen um das Layout zu besprechen.

Könnten Sie bitte einen Probedruck machen?

Für die Zeitung würden wir gerne den selben Text verwenden. Könnten Sie
bitte einen Vorschlag für eine dreispaltige Anzeige machen?

Wir freuen uns auf einen Rückruf.

Beste Grüsse,

Michael Kohlhase

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by tkw1536** [comment]
@kohlhase Wrong recipient?

**Comment by kohlhase** [comment]
Jetzt mit Anhang, ...


On 18/06/15 12:08, Michael Kohlhase wrote:
> Sehr geehrter Herr Höhn,
>
> bitte finden Sie anliegend den Entwurf für die Trauerkarte.
>
> Wir würden gerne heute nachmittag vorbeikommen um das Layout zu besprechen.
>
> Könnten Sie bitte einen Probedruck machen?
>
> Für die Zeitung würden wir gerne den selben Text verwenden. Könnten Sie
> bitte einen Vorschlag für eine dreispaltige Anzeige machen?
>
> Wir freuen uns auf einen Rückruf.
>
> Beste Grüsse,
>
> Michael Kohlhase
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
yes, indeed.

**Pull request merged**
